// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1EHRmD5X3_sDda1KNmn7KRCOJ9-VM3tw',
    appId: '1:71842217772:web:0aefd5af9c3add712ab689',
    messagingSenderId: '71842217772',
    projectId: 'uberclone-20b7f',
    authDomain: 'uberclone-20b7f.firebaseapp.com',
    storageBucket: 'uberclone-20b7f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg_MClfVUscfBg_CvbY6iCqviUzL7vDJQ',
    appId: '1:71842217772:android:ce9140e53081e0382ab689',
    messagingSenderId: '71842217772',
    projectId: 'uberclone-20b7f',
    storageBucket: 'uberclone-20b7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLGNUoO0w_g6F960QgS3nHe2ifWyi6SRw',
    appId: '1:71842217772:ios:94385e0d67b22d822ab689',
    messagingSenderId: '71842217772',
    projectId: 'uberclone-20b7f',
    storageBucket: 'uberclone-20b7f.firebasestorage.app',
    iosBundleId: 'com.example.blocPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLGNUoO0w_g6F960QgS3nHe2ifWyi6SRw',
    appId: '1:71842217772:ios:94385e0d67b22d822ab689',
    messagingSenderId: '71842217772',
    projectId: 'uberclone-20b7f',
    storageBucket: 'uberclone-20b7f.firebasestorage.app',
    iosBundleId: 'com.example.blocPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1EHRmD5X3_sDda1KNmn7KRCOJ9-VM3tw',
    appId: '1:71842217772:web:85095363d7d7d6c52ab689',
    messagingSenderId: '71842217772',
    projectId: 'uberclone-20b7f',
    authDomain: 'uberclone-20b7f.firebaseapp.com',
    storageBucket: 'uberclone-20b7f.firebasestorage.app',
  );
}
